# Team

In [2]:
import pandas as pd

In [3]:
Team_data = pd.read_csv('Resources/Footballteams.csv')
Team_data

,Team,Tournament,Goals,Shots pg,yellow_cards,red_cards,Possession%,Pass%,AerialsWon,Rating,Country
0,Manchester City,Premier League,83,15.8,46,2,60.8,89.4,12.8,7.01,England
1,Bayern Munich,Bundesliga,99,17.1,44,3,58.1,85.5,12.9,6.95,Germany
2,Paris Saint-Germain,Ligue 1,86,15.0,73,7,60.1,89.5,9.5,6.88,France
3,Barcelona,LaLiga,85,15.3,68,2,62.4,89.7,10.6,6.87,Spain
4,Real Madrid,LaLiga,67,14.4,57,2,57.7,87.7,11.8,6.86,Spain
...,...,...,...,...,...,...,...,...,...,...,...
93,Sheffield United,Premier League,20,8.5,73,3,43.0,76.9,19.1,6.46,England
94,Crotone,Serie A,45,9.5,85,4,47.2,80.4,12.7,6.43,Italy
95,Benevento,Serie A,40,11.0,90,5,44.2,77.7,13.4,6.43,Italy
96,Dijon,Ligue 1,25,9.2,75,5,46.9,80.0,14.3,6.42,France
97,Schalke 04,Bundesliga,25,8.9,70,2,46.2,76.5,15.6,6.41,Germany

In [4]:
chelsea_players = pd.read_csv('Resources/chelsea_players.csv')
manchester_players = pd.read_csv('Resources/manchester_players.csv')
psg_players = pd.read_csv('Resources/psg_players.csv')
madrid_players = pd.read_csv('Resources/real_madrid_players.csv')
chelsea_players

                 Player        Club    Nationality
0         Edouard Mendy  Chelsea FC        Senegal
1                  Kepa  Chelsea FC          Spain
2            Kurt Zouma  Chelsea FC         France
3   Andreas Christensen  Chelsea FC        Denmark
4       Antonio Rüdiger  Chelsea FC        Germany
5          Ethan Ampadu  Chelsea FC          Wales
6          Thiago Silva  Chelsea FC         Brazil
7    Jake Clarke-Salter  Chelsea FC        England
8          Ben Chilwell  Chelsea FC        England
9         Marcos Alonso  Chelsea FC          Spain
10              Emerson  Chelsea FC          Italy
11          Reece James  Chelsea FC        England
12    César Azpilicueta  Chelsea FC          Spain
13         N'Golo Kanté  Chelsea FC         France
14             Jorginho  Chelsea FC          Italy
15        Mateo Kovacic  Chelsea FC        Croatia
16         Ross Barkley  Chelsea FC        England
17   Ruben Loftus-Cheek  Chelsea FC        England
18      Conor Gallagher  Chelsea FC        England
19          Mason Mount  Chelsea FC        England
20          Kai Havertz  Chelsea FC        Germany
21         Hakim Ziyech  Chelsea FC        Morocco
22   Charly Musonda Jr.  Chelsea FC        Belgium
23   Callum Hudson-Odoi  Chelsea FC        England
24    Christian Pulisic  Chelsea FC  United States
25          Timo Werner  Chelsea FC        Germany
26        Tammy Abraham  Chelsea FC        England
27      Michy Batshuayi  Chelsea FC        Belgium
28       Olivier Giroud  Chelsea FC         France

In [5]:
chelsea_group = chelsea_players.groupby("Nationality").agg({"Nationality":["count"]})
#nationality_group.reset_index(inplace=True)
#nationality_group.columns = ["Nationality","Count"]
#Sorted_nationalities = nationality_group.sort_values(by = "Count", ascending = False)
#Sorted_nationalities

In [6]:
manchester_players

                 Player             Club    Nationality
0               Ederson  Manchester City         Brazil
1          Zack Steffen  Manchester City  United States
2            Rúben Dias  Manchester City       Portugal
3       Aymeric Laporte  Manchester City          Spain
4            Nathan Aké  Manchester City    Netherlands
5           John Stones  Manchester City        England
6      Philippe Sandler  Manchester City    Netherlands
7   Oleksandr Zinchenko  Manchester City        Ukraine
8        Benjamin Mendy  Manchester City         France
9          João Cancelo  Manchester City       Portugal
10          Kyle Walker  Manchester City        England
11                Rodri  Manchester City          Spain
12          Fernandinho  Manchester City         Brazil
13       Ilkay Gündogan  Manchester City        Germany
14      Kevin De Bruyne  Manchester City        Belgium
15       Bernardo Silva  Manchester City       Portugal
16      Raheem Sterling  Manchester City        England
17           Phil Foden  Manchester City        England
18        Ferran Torres  Manchester City          Spain
19         Riyad Mahrez  Manchester City        Algeria
20      Patrick Roberts  Manchester City        England
21        Gabriel Jesus  Manchester City         Brazil

In [7]:
psg_players

                 Player                 Club  Nationality
0          Keylor Navas  Paris Saint-Germain   Costa Rica
1           Sergio Rico  Paris Saint-Germain        Spain
2          Marcin Bulka  Paris Saint-Germain       Poland
3   Alexandre Letellier  Paris Saint-Germain       France
4    Garissone Innocent  Paris Saint-Germain        Haiti
5         Denis Franchi  Paris Saint-Germain        Italy
6            Marquinhos  Paris Saint-Germain       Brazil
7      Presnel Kimpembe  Paris Saint-Germain       France
8          Thilo Kehrer  Paris Saint-Germain      Germany
9          Abdou Diallo  Paris Saint-Germain      Senegal
10     Timothée Pembélé  Paris Saint-Germain       France
11          Juan Bernat  Paris Saint-Germain        Spain
12       Layvin Kurzawa  Paris Saint-Germain       France
13          Colin Dagba  Paris Saint-Germain       France
14      Leandro Paredes  Paris Saint-Germain    Argentina
15       Danilo Pereira  Paris Saint-Germain     Portugal
16        Idrissa Gueye  Paris Saint-Germain      Senegal
17       Marco Verratti  Paris Saint-Germain        Italy
18              Rafinha  Paris Saint-Germain       Brazil
19        Ander Herrera  Paris Saint-Germain        Spain
20          Xavi Simons  Paris Saint-Germain  Netherlands
21    Bandiougou Fadiga  Paris Saint-Germain       France
22       Edouard Michut  Paris Saint-Germain       France
23        Ismaël Gharbi  Paris Saint-Germain       France
24               Neymar  Paris Saint-Germain       Brazil
25       Julian Draxler  Paris Saint-Germain      Germany
26        Pablo Sarabia  Paris Saint-Germain        Spain
27       Ángel Di María  Paris Saint-Germain    Argentina
28        Kylian Mbappé  Paris Saint-Germain       France
29         Mauro Icardi  Paris Saint-Germain    Argentina
30    Arnaud Kalimuendo  Paris Saint-Germain       France
31         Kenny Nagera  Paris Saint-Germain       France

In [8]:
madrid_players

              Player         Club         Nationality
0   Thibaut Courtois  Real Madrid             Belgium
1       Andriy Lunin  Real Madrid             Ukraine
2     Raphaël Varane  Real Madrid              France
3       Éder Militão  Real Madrid              Brazil
4    Nacho Fernández  Real Madrid               Spain
5      Ferland Mendy  Real Madrid              France
6            Marcelo  Real Madrid              Brazil
7    Daniel Carvajal  Real Madrid               Spain
8   Álvaro Odriozola  Real Madrid               Spain
9           Casemiro  Real Madrid              Brazil
10     Fede Valverde  Real Madrid             Uruguay
11        Toni Kroos  Real Madrid             Germany
12       Luka Modric  Real Madrid             Croatia
13   Martin Ødegaard  Real Madrid              Norway
14              Isco  Real Madrid               Spain
15       Eden Hazard  Real Madrid             Belgium
16   Vinícius Júnior  Real Madrid              Brazil
17     Marco Asensio  Real Madrid               Spain
18           Rodrygo  Real Madrid              Brazil
19     Lucas Vázquez  Real Madrid               Spain
20     Karim Benzema  Real Madrid              France
21        Luka Jovic  Real Madrid              Serbia
22      Mariano Díaz  Real Madrid  Dominican Republic

In [9]:
frames = [chelsea_players, manchester_players, psg_players,madrid_players]
all_nationalities = pd.concat(frames)
all_nationalities

                 Player         Club         Nationality
0         Edouard Mendy   Chelsea FC             Senegal
1                  Kepa   Chelsea FC               Spain
2            Kurt Zouma   Chelsea FC              France
3   Andreas Christensen   Chelsea FC             Denmark
4       Antonio Rüdiger   Chelsea FC             Germany
..                  ...          ...                 ...
18              Rodrygo  Real Madrid              Brazil
19        Lucas Vázquez  Real Madrid               Spain
20        Karim Benzema  Real Madrid              France
21           Luka Jovic  Real Madrid              Serbia
22         Mariano Díaz  Real Madrid  Dominican Republic

[106 rows x 3 columns]

In [10]:
nationality_group = all_nationalities.groupby(["Club","Nationality"]).agg({"Nationality":["count"]})
nationality_group.reset_index(inplace=True)
nationality_group.columns = ["Club","Nationality","Count"]
Sorted_nationalities = nationality_group.sort_values(by = "Club", ascending = False)
Sorted_nationalities

                   Club         Nationality  Count
46          Real Madrid             Uruguay      1
41          Real Madrid             Germany      1
37          Real Madrid              Brazil      5
38          Real Madrid             Croatia      1
39          Real Madrid  Dominican Republic      1
40          Real Madrid              France      3
36          Real Madrid             Belgium      2
42          Real Madrid              Norway      1
43          Real Madrid              Serbia      1
44          Real Madrid               Spain      6
45          Real Madrid             Ukraine      1
24  Paris Saint-Germain           Argentina      3
35  Paris Saint-Germain               Spain      4
34  Paris Saint-Germain             Senegal      2
33  Paris Saint-Germain            Portugal      1
32  Paris Saint-Germain              Poland      1
31  Paris Saint-Germain         Netherlands      1
30  Paris Saint-Germain               Italy      2
29  Paris Saint-Germain               Haiti      1
28  Paris Saint-Germain             Germany      2
27  Paris Saint-Germain              France     11
26  Paris Saint-Germain          Costa Rica      1
25  Paris Saint-Germain              Brazil      3
23      Manchester City       United States      1
21      Manchester City               Spain      3
20      Manchester City            Portugal      3
19      Manchester City         Netherlands      2
18      Manchester City             Germany      1
17      Manchester City              France      1
16      Manchester City             England      5
15      Manchester City              Brazil      3
14      Manchester City             Belgium      1
13      Manchester City             Algeria      1
22      Manchester City             Ukraine      1
1            Chelsea FC              Brazil      1
6            Chelsea FC             Germany      3
2            Chelsea FC             Croatia      1
3            Chelsea FC             Denmark      1
4            Chelsea FC             England      9
5            Chelsea FC              France      3
12           Chelsea FC               Wales      1
7            Chelsea FC               Italy      2
8            Chelsea FC             Morocco      1
9            Chelsea FC             Senegal      1
10           Chelsea FC               Spain      3
11           Chelsea FC       United States      1
0            Chelsea FC             Belgium      2

In [12]:
html_table = nationality_group.to_html()
html_table

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Club</th>\n      <th>Nationality</th>\n      <th>Count</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Chelsea FC</td>\n      <td>Belgium</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Chelsea FC</td>\n      <td>Brazil</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Chelsea FC</td>\n      <td>Croatia</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Chelsea FC</td>\n      <td>Denmark</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Chelsea FC</td>\n      <td>England</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Chelsea FC</td>\n      <td>France</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Chelsea FC</td>\n      <td>Germany</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Chelsea FC</td>\n      <td>Italy</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Chelsea FC</td>\n      <td>Morocco</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Chelsea FC</td>\n      <td>Senegal</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>Chelsea FC</td>\n      <td>Spain</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Chelsea FC</td>\n      <td>United States</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>Chelsea FC</td>\n      <td>Wales</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>Manchester City</td>\n      <td>Algeria</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>Manchester City</td>\n      <td>Belgium</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>Manchester City</td>\n      <td>Brazil</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>Manchester City</td>\n      <td>England</td>\n      <td>5</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>Manchester City</td>\n      <td>France</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>Manchester City</td>\n      <td>Germany</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>Manchester City</td>\n      <td>Netherlands</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>Manchester City</td>\n      <td>Portugal</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>Manchester City</td>\n      <td>Spain</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>Manchester City</td>\n      <td>Ukraine</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>Manchester City</td>\n      <td>United States</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>Paris Saint-Germain</td>\n      <td>Argentina</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>25</th>\n      <td>Paris Saint-Germain</td>\n      <td>Brazil</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>26</th>\n      <td>Paris Saint-Germain</td>\n      <td>Costa Rica</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>27</th>\n      <td>Paris Saint-Germain</td>\n      <td>France</td>\n      <td>11</td>\n    </tr>\n    <tr>\n      <th>28</th>\n      <td>Paris Saint-Germain</td>\n      <td>Germany</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>29</th>\n      <td>Paris Saint-Germain</td>\n      <td>Haiti</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>30</th>\n      <td>Paris Saint-Germain</td>\n      <td>Italy</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>31</th>\n      <td>Paris Saint-Germain</td>\n      <td>Netherlands</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>32</th>\n      <td>Paris Saint-Germain</td>\n      <td>Poland</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>33</th>\n      <td>Paris Saint-Germain</td>\n      <td>Portugal</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>34</th>\n      <td>Paris Saint-Germain</td>\n      <td>Senegal</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>35</th>\n      <td>Paris Saint-Germain</td>\n      <td>Spain</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>36</th>\n      <td>Real Madrid</td>\n      <td>Belgium</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>37</th>\n      <td>Real Madrid</td>\n      <td>Brazil</td>\n      <td>5</td>\n    </tr>\n    <tr>\n      <th>38</th>\n      <td>Real Madrid</td>\n      <td>Croatia</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>39</th>\n      <td>Real Madrid</td>\n      <td>Dominican Republic</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>40</th>\n      <td>Real Madrid</td>\n      <td>France</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>41</th>\n      <td>Real Madrid</td>\n      <td>Germany</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>42</th>\n      <td>Real Madrid</td>\n      <td>Norway</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>43</th>\n      <td>Real Madrid</td>\n      <td>Serbia</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>44</th>\n      <td>Real Madrid</td>\n      <td>Spain</td>\n      <td>6</td>\n    </tr>\n    <tr>\n      <th>45</th>\n      <td>Real Madrid</td>\n      <td>Ukraine</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>46</th>\n      <td>Real Madrid</td>\n      <td>Uruguay</td>\n      <td>1</td>\n    </tr>\n  </tbody>\n</table>'

In [16]:
nationality_group.to_html('Data_table.html')