# Team

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import json
from sqlalchemy import create_engine
from geojson import Feature, FeatureCollection, Point

In [2]:
Coordinates = pd.read_csv('Resources/world_country_latitude_and_longitude_values.csv')
Coordinates

                  Country  Latitude  Longitude
0                 Andorra     42.50       1.50
1    United Arab Emirates     24.00      54.00
2             Afghanistan     33.00      65.00
3     Antigua and Barbuda     17.05     -61.80
4                Anguilla     18.25     -63.17
..                    ...       ...        ...
235                 Yemen     15.00      48.00
236               Mayotte    -12.83      45.17
237          South Africa    -29.00      24.00
238                Zambia    -15.00      30.00
239              Zimbabwe    -20.00      30.00

[240 rows x 3 columns]

In [3]:
Team_data = pd.read_csv('Resources/Footballteams.csv')
Team_data['Country']=Team_data['Country'].apply(lambda x: x.strip())
Team_data

,Team,Tournament,Goals,Shots pg,yellow_cards,red_cards,Possession%,Pass%,AerialsWon,Rating,Country
0,Manchester City,Premier League,83,15.8,46,2,60.8,89.4,12.8,7.01,England
1,Bayern Munich,Bundesliga,99,17.1,44,3,58.1,85.5,12.9,6.95,Germany
2,Paris Saint-Germain,Ligue 1,86,15.0,73,7,60.1,89.5,9.5,6.88,France
3,Barcelona,LaLiga,85,15.3,68,2,62.4,89.7,10.6,6.87,Spain
4,Real Madrid,LaLiga,67,14.4,57,2,57.7,87.7,11.8,6.86,Spain
...,...,...,...,...,...,...,...,...,...,...,...
93,Sheffield United,Premier League,20,8.5,73,3,43.0,76.9,19.1,6.46,England
94,Crotone,Serie A,45,9.5,85,4,47.2,80.4,12.7,6.43,Italy
95,Benevento,Serie A,40,11.0,90,5,44.2,77.7,13.4,6.43,Italy
96,Dijon,Ligue 1,25,9.2,75,5,46.9,80.0,14.3,6.42,France
97,Schalke 04,Bundesliga,25,8.9,70,2,46.2,76.5,15.6,6.41,Germany

In [17]:
Team_data_Final = pd.merge(Team_data,Coordinates,on = "Country")
Team_data_Final

,Team,Tournament,Goals,Shots pg,yellow_cards,red_cards,Possession%,Pass%,AerialsWon,Rating,Country,Latitude,Longitude
0,Manchester City,Premier League,83,15.8,46,2,60.8,89.4,12.8,7.01,England,54.00,-2.00
1,Manchester United,Premier League,73,13.8,64,1,54.5,84.8,14.5,6.85,England,54.00,-2.00
2,Aston Villa,Premier League,55,13.7,63,4,49.1,78.6,19.4,6.84,England,54.00,-2.00
3,Chelsea,Premier League,58,14.6,49,3,58.6,87.0,15.2,6.83,England,54.00,-2.00
4,Liverpool,Premier League,68,16.0,40,0,59.0,85.7,14.3,6.82,England,54.00,-2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,Fiorentina,Serie A,47,9.8,86,5,46.8,81.0,14.2,6.52,Italy,42.83,12.83
94,Spezia,Serie A,52,10.2,92,5,51.6,81.1,14.4,6.50,Italy,42.83,12.83
95,Parma Calcio 1913,Serie A,39,10.4,91,1,48.4,82.5,16.9,6.49,Italy,42.83,12.83
96,Crotone,Serie A,45,9.5,85,4,47.2,80.4,12.7,6.43,Italy,42.83,12.83
97,Benevento,Serie A,40,11.0,90,5,44.2,77.7,13.4,6.43,Italy,42.83,12.83

In [5]:
# columns used for constructing geojson object
features = Team_data_Final.apply(
    lambda row: Feature(geometry=Point((float(row['Longitude']), float(row['Latitude'])))),
    axis=1).tolist()

# all the other columns used as properties
properties = Team_data_Final.drop(['Latitude', 'Longitude'], axis=1).to_dict('records')

# whole geojson object
feature_collection = FeatureCollection(features=features, properties=properties)

In [17]:
with open('Team_Data.geojson', 'w', encoding='utf-8') as f:
    json.dump(feature_collection, f, ensure_ascii=False)

In [4]:
engine = create_engine('sqlite:///football_team_data.db')

In [5]:
Team_data.to_sql('premier_league_team_data', con=engine, if_exists='replace', index=False)

In [6]:
engine.execute("SELECT * FROM premier_league_team_data").fetchall()

[('Manchester City', 'Premier League', 83, 15.8, 46, 2, 60.8, 89.4, 12.8, 7.01, 'England '),
 ('Bayern Munich', 'Bundesliga', 99, 17.1, 44, 3, 58.1, 85.5, 12.9, 6.95, 'Germany '),
 ('Paris Saint-Germain', 'Ligue 1', 86, 15.0, 73, 7, 60.1, 89.5, 9.5, 6.88, 'France '),
 ('Barcelona', 'LaLiga', 85, 15.3, 68, 2, 62.4, 89.7, 10.6, 6.87, 'Spain'),
 ('Real Madrid', 'LaLiga', 67, 14.4, 57, 2, 57.7, 87.7, 11.8, 6.86, 'Spain'),
 ('Manchester United', 'Premier League', 73, 13.8, 64, 1, 54.5, 84.8, 14.5, 6.85, 'England '),
 ('Juventus', 'Serie A', 77, 15.7, 76, 6, 55.4, 88.3, 11.4, 6.85, 'Italy '),
 ('Aston Villa', 'Premier League', 55, 13.7, 63, 4, 49.1, 78.6, 19.4, 6.84, 'England '),
 ('Borussia Dortmund', 'Bundesliga', 75, 14.6, 43, 1, 57.5, 85.5, 12.8, 6.84, 'Germany '),
 ('Atletico Madrid', 'LaLiga', 67, 12.1, 100, 0, 51.8, 83.1, 14.4, 6.84, 'Spain'),
 ('Atalanta', 'Serie A', 90, 16.3, 66, 3, 53.5, 83.5, 16.8, 6.84, 'Italy '),
 ('Chelsea', 'Premier League', 58, 14.6, 49, 3, 58.6, 87.0, 15.2, 6.83, 'England '),
 ('Liverpool', 'Premier League', 68, 16.0, 40, 0, 59.0, 85.7, 14.3, 6.82, 'England '),
 ('AC Milan', 'Serie A', 74, 14.7, 80, 4, 51.4, 84.0, 15.2, 6.82, 'Italy '),
 ('Lille', 'Ligue 1', 64, 12.8, 67, 2, 52.6, 83.5, 15.8, 6.82, 'France '),
 ('Tottenham', 'Premier League', 68, 11.7, 53, 2, 51.3, 81.8, 16.4, 6.81, 'England '),
 ('Napoli', 'Serie A', 86, 17.0, 71, 3, 54.1, 87.0, 11.1, 6.81, 'Italy '),
 ('Leicester', 'Premier League', 68, 12.8, 61, 0, 53.2, 82.1, 16.2, 6.8, 'England '),
 ('Wolfsburg', 'Bundesliga', 61, 14.1, 56, 3, 51.0, 78.0, 16.9, 6.8, 'Germany '),
 ('Inter', 'Serie A', 89, 14.5, 59, 2, 52.0, 87.0, 11.8, 6.8, 'Italy '),
 ('Lyon', 'Ligue 1', 81, 16.1, 60, 10, 53.6, 84.7, 14.3, 6.8, 'France '),
 ('RB Leipzig', 'Bundesliga', 60, 16.0, 57, 0, 57.3, 83.2, 18.6, 6.78, 'Germany '),
 ('Leeds', 'Premier League', 62, 13.7, 61, 1, 55.1, 80.8, 14.5, 6.77, 'England '),
 ('West Ham', 'Premier League', 62, 12.3, 48, 3, 44.5, 77.8, 19.9, 6.77, 'England '),
 ('Everton', 'Premier League', 47, 10.5, 59, 2, 47.3, 81.4, 17.7, 6.73, 'England '),
 ('Bayer Leverkusen', 'Bundesliga', 53, 13.0, 58, 0, 57.3, 84.4, 13.1, 6.73, 'Germany '),
 ('Eintracht Frankfurt', 'Bundesliga', 69, 13.2, 80, 1, 52.4, 79.6, 17.9, 6.73, 'Germany '),
 ('Monaco', 'Ligue 1', 76, 12.8, 74, 7, 54.2, 82.7, 16.5, 6.73, 'France '),
 ('Roma', 'Serie A', 68, 14.3, 84, 3, 51.5, 84.5, 12.1, 6.71, 'Italy '),
 ('Sevilla', 'LaLiga', 53, 12.1, 75, 2, 58.7, 86.2, 16.6, 6.7, 'Spain'),
 ('Borussia M.Gladbach', 'Bundesliga', 64, 13.4, 61, 2, 51.5, 82.0, 15.3, 6.7, 'Germany '),
 ('Arsenal', 'Premier League', 55, 12.1, 47, 5, 52.7, 85.0, 13.5, 6.69, 'England '),
 ('Rennes', 'Ligue 1', 52, 13.5, 80, 5, 56.8, 85.6, 16.9, 6.69, 'France '),
 ('VfB Stuttgart', 'Bundesliga', 56, 13.4, 63, 2, 51.5, 81.1, 16.3, 6.68, 'Germany '),
 ('Wolverhampton Wanderers', 'Premier League', 36, 12.2, 53, 1, 49.7, 83.2, 15.3, 6.67, 'England '),
 ('Sassuolo', 'Serie A', 64, 13.9, 74, 4, 58.2, 87.8, 10.9, 6.67, 'Italy '),
 ('Metz', 'Ligue 1', 44, 11.5, 82, 4, 46.9, 79.8, 16.1, 6.66, 'France '),
 ('Villarreal', 'LaLiga', 60, 10.7, 65, 5, 54.3, 84.4, 13.0, 6.66, 'Spain'),
 ('Real Sociedad', 'LaLiga', 59, 11.3, 81, 1, 53.7, 80.8, 17.9, 6.65, 'Spain'),
 ('Brighton', 'Premier League', 40, 12.8, 45, 6, 50.7, 81.3, 14.2, 6.65, 'England '),
 ('Real Betis', 'LaLiga', 50, 11.7, 87, 8, 52.9, 82.0, 16.4, 6.64, 'Spain'),
 ('Burnley', 'Premier League', 33, 10.1, 48, 0, 43.5, 71.6, 23.4, 6.64, 'England '),
 ('Lens', 'Ligue 1', 55, 11.7, 84, 7, 51.1, 81.8, 17.4, 6.64, 'France '),
 ('Brest', 'Ligue 1', 50, 11.8, 60, 4, 49.4, 81.3, 18.6, 6.64, 'France '),
 ('Fulham', 'Premier League', 27, 11.6, 67, 3, 50.0, 81.2, 17.2, 6.63, 'England '),
 ('Marseille', 'Ligue 1', 54, 10.0, 94, 9, 52.4, 82.0, 14.9, 6.63, 'France '),
 ('Sampdoria', 'Serie A', 52, 11.3, 81, 3, 46.1, 78.5, 16.8, 6.63, 'Italy '),
 ('Montpellier', 'Ligue 1', 60, 12.2, 65, 7, 46.4, 78.8, 17.9, 6.63, 'France '),
 ('Nice', 'Ligue 1', 50, 10.8, 69, 4, 53.4, 85.6, 10.5, 6.63, 'France '),
 ('Hoffenheim', 'Bundesliga', 52, 12.6, 65, 4, 50.8, 80.7, 15.7, 6.63, 'Germany '),
 ('Southampton', 'Premier League', 47, 11.2, 52, 3, 51.4, 79.3, 14.1, 6.62, 'England '),
 ('Newcastle United', 'Premier League', 46, 10.4, 61, 3, 41.6, 76.0, 17.1, 6.62, 'England '),
 ('Lazio', 'Serie A', 61, 13.8, 100, 5, 52.2, 83.8, 14.6, 6.62, 'Italy '),
 ('Nantes', 'Ligue 1', 47, 10.8, 68, 4, 45.2, 77.0, 18.1, 6.62, 'France '),
 ('Union Berlin', 'Bundesliga', 50, 11.7, 55, 2, 45.9, 76.2, 17.6, 6.62, 'Germany '),
 ('Strasbourg', 'Ligue 1', 49, 11.3, 56, 3, 46.5, 78.3, 18.3, 6.61, 'France '),
 ('Crystal Palace', 'Premier League', 41, 9.2, 54, 2, 42.9, 76.1, 18.3, 6.61, 'England '),
 ('Freiburg', 'Bundesliga', 52, 11.4, 63, 0, 47.5, 78.1, 17.5, 6.6, 'Germany '),
 ('Valencia', 'LaLiga', 50, 10.3, 77, 5, 47.9, 79.4, 16.3, 6.6, 'Spain'),
 ('Celta Vigo', 'LaLiga', 55, 9.4, 104, 5, 52.0, 79.9, 16.5, 6.6, 'Spain'),
 ('Reims', 'Ligue 1', 42, 9.6, 75, 8, 46.3, 80.7, 13.4, 6.6, 'France '),
 ('Torino', 'Serie A', 50, 12.2, 72, 4, 48.0, 80.5, 16.1, 6.59, 'Italy '),
 ('Verona', 'Serie A', 43, 10.6, 91, 1, 49.6, 76.3, 20.6, 6.59, 'Italy '),
 ('Saint-Etienne', 'Ligue 1', 42, 11.6, 76, 2, 49.0, 79.3, 16.4, 6.59, 'France '),
 ('Bordeaux', 'Ligue 1', 42, 11.1, 74, 4, 50.2, 83.3, 15.4, 6.59, 'France '),
 ('Hertha Berlin', 'Bundesliga', 41, 11.3, 63, 3, 49.8, 79.5, 15.8, 6.58, 'Germany '),
 ('Cagliari', 'Serie A', 43, 11.4, 73, 3, 45.8, 79.8, 17.2, 6.58, 'Italy '),
 ('Mainz 05', 'Bundesliga', 39, 11.1, 61, 1, 42.7, 71.3, 18.3, 6.57, 'Germany '),
 ('Bologna', 'Serie A', 51, 13.1, 78, 4, 50.7, 81.5, 15.1, 6.56, 'Italy '),
 ('Augsburg', 'Bundesliga', 36, 9.9, 65, 4, 44.0, 73.6, 16.8, 6.56, 'Germany '),
 ('Udinese', 'Serie A', 42, 10.9, 63, 2, 47.2, 82.5, 13.1, 6.55, 'Italy '),
 ('SD Huesca', 'LaLiga', 34, 10.7, 68, 2, 48.7, 79.8, 15.7, 6.55, 'Spain'),
 ('Athletic Bilbao', 'LaLiga', 46, 10.6, 81, 3, 49.4, 78.5, 17.9, 6.54, 'Spain'),
 ('Osasuna', 'LaLiga', 37, 9.8, 74, 5, 44.6, 70.2, 26.8, 6.54, 'Spain'),
 ('Lorient', 'Ligue 1', 50, 11.2, 67, 3, 45.9, 78.8, 13.7, 6.54, 'France '),
 ('Genoa', 'Serie A', 47, 9.0, 85, 2, 46.1, 79.7, 13.7, 6.54, 'Italy '),
 ('Arminia Bielefeld', 'Bundesliga', 26, 9.8, 52, 1, 44.1, 74.6, 22.2, 6.53, 'Germany '),
 ('Angers', 'Ligue 1', 40, 10.7, 63, 2, 47.1, 81.3, 13.2, 6.53, 'France '),
 ('Eibar', 'LaLiga', 29, 11.9, 67, 3, 49.2, 72.6, 24.4, 6.53, 'Spain'),
 ('Werder Bremen', 'Bundesliga', 36, 10.6, 63, 3, 45.2, 76.2, 18.3, 6.52, 'Germany '),
 ('Fiorentina', 'Serie A', 47, 9.8, 86, 5, 46.8, 81.0, 14.2, 6.52, 'Italy '),
 ('Nimes', 'Ligue 1', 40, 10.3, 57, 5, 45.8, 77.5, 14.0, 6.52, 'France '),
 ('West Bromwich Albion', 'Premier League', 35, 8.9, 51, 4, 41.0, 72.2, 19.1, 6.51, 'England '),
 ('FC Koln', 'Bundesliga', 34, 10.6, 62, 1, 47.1, 77.3, 18.5, 6.51, 'Germany '),
 ('Deportivo Alaves', 'LaLiga', 36, 9.1, 87, 8, 44.6, 72.9, 22.6, 6.5, 'Spain'),
 ('Levante', 'LaLiga', 46, 10.1, 70, 1, 51.5, 80.1, 12.2, 6.5, 'Spain'),
 ('Spezia', 'Serie A', 52, 10.2, 92, 5, 51.6, 81.1, 14.4, 6.5, 'Italy '),
 ('Getafe', 'LaLiga', 28, 9.5, 117, 7, 44.4, 66.5, 22.8, 6.49, 'Spain'),
 ('Parma Calcio 1913', 'Serie A', 39, 10.4, 91, 1, 48.4, 82.5, 16.9, 6.49, 'Italy '),
 ('Elche', 'LaLiga', 34, 7.1, 95, 3, 48.1, 81.5, 13.2, 6.48, 'Spain'),
 ('Granada', 'LaLiga', 47, 9.4, 96, 6, 43.4, 70.0, 18.3, 6.47, 'Spain'),
 ('Cadiz', 'LaLiga', 36, 8.0, 77, 3, 38.5, 68.8, 18.5, 6.47, 'Spain'),
 ('Real Valladolid', 'LaLiga', 34, 9.7, 93, 4, 46.2, 74.8, 17.1, 6.46, 'Spain'),
 ('Sheffield United', 'Premier League', 20, 8.5, 73, 3, 43.0, 76.9, 19.1, 6.46, 'England '),
 ('Crotone', 'Serie A', 45, 9.5, 85, 4, 47.2, 80.4, 12.7, 6.43, 'Italy '),
 ('Benevento', 'Serie A', 40, 11.0, 90, 5, 44.2, 77.7, 13.4, 6.43, 'Italy '),
 ('Dijon', 'Ligue 1', 25, 9.2, 75, 5, 46.9, 80.0, 14.3, 6.42, 'France '),
 ('Schalke 04', 'Bundesliga', 25, 8.9, 70, 2, 46.2, 76.5, 15.6, 6.41, 'Germany ')]

In [ ]:
Country_Rating = Team_data.groupby("Country").agg({"Rating":["sum"]})
Country_Goals = Team_data.groupby("Country").agg({"Goals":["sum"]})
Country_Shots = Team_data.groupby("Country").agg({"Shots pg":["sum"]})
Country_yellow_cards = Team_data.groupby("Country").agg({"yellow_cards":["sum"]})
Country_red_cards = Team_data.groupby("Country").agg({"red_cards":["sum"]})

Country_summary1 = pd.merge(Country_Rating,Country_Goals,on = "Country")
Country_summary2 = pd.merge(Country_summary1,Country_Shots,on = "Country")
Country_summary3 = pd.merge(Country_summary2,Country_yellow_cards,on = "Country")
Country_summary = pd.merge(Country_summary3,Country_red_cards,on = "Country")

#Reset the Index
Country_summary.reset_index(inplace=True)
#Assign name for the column variables
Country_summary.columns = ["Country","Rating","Goals","Shots","Yellow_Cards","Red_Cards"]

In [ ]:
football_teams_summary = pd.merge(Country_summary,Coordinates,on = "Country")
football_teams_summary.to_csv(r'Country_summary.csv')
football_teams_summary

import csv, json

csvFilePath = "Country_summary.csv"  ## path to file
jsonFilePath = "Country_summary.json"   ## change to wanted file name

data = {}
with open(csvFilePath) as csvFile:
    csvReader = csv.DictReader(csvFile)
    for rows in csvReader:
        id = rows['Country']
        data[id] = rows

with open(jsonFilePath, 'w') as jsonFile:
    jsonFile.write(json.dumps(data, indent=4))

In [11]:
chelsea_players = pd.read_csv('Resources/chelsea_players.csv')
chelsea_players_Final = pd.merge(chelsea_players,Coordinates,how='left', left_on=['Nationality'], right_on=['Country'])

# columns used for constructing geojson object
features = chelsea_players_Final.apply(
    lambda row: Feature(geometry=Point((float(row['Longitude']), float(row['Latitude'])))),
    axis=1).tolist()

# all the other columns used as properties
properties = chelsea_players_Final.drop(['Latitude', 'Longitude'], axis=1).to_dict('records')

# whole geojson object
feature_collection = FeatureCollection(features=features, properties=properties)

with open('chelsea_players_Final.geojson', 'w', encoding='utf-8') as f:
    json.dump(feature_collection, f, ensure_ascii=False)

chelsea_players_Final

,Player,Club,Nationality,Country,Latitude,Longitude
0,Edouard Mendy,Chelsea FC,Senegal,Senegal,14.00,-14.00
1,Kepa,Chelsea FC,Spain,Spain,40.00,-4.00
2,Kurt Zouma,Chelsea FC,France,France,46.00,2.00
3,Andreas Christensen,Chelsea FC,Denmark,Denmark,56.00,10.00
4,Antonio Rüdiger,Chelsea FC,Germany,Germany,51.00,9.00
5,Ethan Ampadu,Chelsea FC,Wales,NaN,NaN,NaN
6,Thiago Silva,Chelsea FC,Brazil,Brazil,-10.00,-55.00
7,Jake Clarke-Salter,Chelsea FC,England,England,54.00,-2.00
8,Ben Chilwell,Chelsea FC,England,England,54.00,-2.00
9,Marcos Alonso,Chelsea FC,Spain,Spain,40.00,-4.00
10,Emerson,Chelsea FC,Italy,Italy,42.83,12.83
11,Reece James,Chelsea FC,England,England,54.00,-2.00
12,César Azpilicueta,Chelsea FC,Spain,Spain,40.00,-4.00
13,N'Golo Kanté,Chelsea FC,France,France,46.00,2.00
14,Jorginho,Chelsea FC,Italy,Italy,42.83,12.83
15,Mateo Kovacic,Chelsea FC,Croatia,Croatia,45.17,15.50
16,Ross Barkley,Chelsea FC,England,England,54.00,-2.00
17,Ruben Loftus-Cheek,Chelsea FC,England,England,54.00,-2.00
18,Conor Gallagher,Chelsea FC,England,England,54.00,-2.00
19,Mason Mount,Chelsea FC,England,England,54.00,-2.00
20,Kai Havertz,Chelsea FC,Germany,Germany,51.00,9.00
21,Hakim Ziyech,Chelsea FC,Morocco,Morocco,32.00,-5.00
22,Charly Musonda Jr.,Chelsea FC,Belgium,Belgium,50.83,4.00
23,Callum Hudson-Odoi,Chelsea FC,England,England,54.00,-2.00
24,Christian Pulisic,Chelsea FC,United States,United States,38.00,-97.00
25,Timo Werner,Chelsea FC,Germany,Germany,51.00,9.00
26,Tammy Abraham,Chelsea FC,England,England,54.00,-2.00
27,Michy Batshuayi,Chelsea FC,Belgium,Belgium,50.83,4.00
28,Olivier Giroud,Chelsea FC,France,France,46.00,2.00

In [ ]:
manchester_players = pd.read_csv('Resources/manchester_players.csv')
psg_players = pd.read_csv('Resources/psg_players.csv')
madrid_players = pd.read_csv('Resources/real_madrid_players.csv')
chelsea_players

In [14]:
manchester_players = pd.read_csv('Resources/manchester_players.csv')
manchester_players_Final = pd.merge(manchester_players,Coordinates,how='left', left_on=['Nationality'], right_on=['Country'])

# columns used for constructing geojson object
features = manchester_players_Final.apply(
    lambda row: Feature(geometry=Point((float(row['Longitude']), float(row['Latitude'])))),
    axis=1).tolist()

# all the other columns used as properties
properties = manchester_players_Final.drop(['Latitude', 'Longitude'], axis=1).to_dict('records')

# whole geojson object
feature_collection = FeatureCollection(features=features, properties=properties)

with open('manchester_players_Final.geojson', 'w', encoding='utf-8') as f:
    json.dump(feature_collection, f, ensure_ascii=False)

manchester_players_Final

,Player,Club,Nationality,Country,Latitude,Longitude
0,Ederson,Manchester City,Brazil,Brazil,-10.00,-55.00
1,Zack Steffen,Manchester City,United States,United States,38.00,-97.00
2,Rúben Dias,Manchester City,Portugal,Portugal,39.50,-8.00
3,Aymeric Laporte,Manchester City,Spain,Spain,40.00,-4.00
4,Nathan Aké,Manchester City,Netherlands,Netherlands,52.50,5.75
5,John Stones,Manchester City,England,England,54.00,-2.00
6,Philippe Sandler,Manchester City,Netherlands,Netherlands,52.50,5.75
7,Oleksandr Zinchenko,Manchester City,Ukraine,Ukraine,49.00,32.00
8,Benjamin Mendy,Manchester City,France,France,46.00,2.00
9,João Cancelo,Manchester City,Portugal,Portugal,39.50,-8.00
10,Kyle Walker,Manchester City,England,England,54.00,-2.00
11,Rodri,Manchester City,Spain,Spain,40.00,-4.00
12,Fernandinho,Manchester City,Brazil,Brazil,-10.00,-55.00
13,Ilkay Gündogan,Manchester City,Germany,Germany,51.00,9.00
14,Kevin De Bruyne,Manchester City,Belgium,Belgium,50.83,4.00
15,Bernardo Silva,Manchester City,Portugal,Portugal,39.50,-8.00
16,Raheem Sterling,Manchester City,England,England,54.00,-2.00
17,Phil Foden,Manchester City,England,England,54.00,-2.00
18,Ferran Torres,Manchester City,Spain,Spain,40.00,-4.00
19,Riyad Mahrez,Manchester City,Algeria,Algeria,28.00,3.00
20,Patrick Roberts,Manchester City,England,England,54.00,-2.00
21,Gabriel Jesus,Manchester City,Brazil,Brazil,-10.00,-55.00

In [15]:
psg_players = pd.read_csv('Resources/psg_players.csv')
psg_players_Final = pd.merge(psg_players,Coordinates,how='left', left_on=['Nationality'], right_on=['Country'])

# columns used for constructing geojson object
features = psg_players_Final.apply(
    lambda row: Feature(geometry=Point((float(row['Longitude']), float(row['Latitude'])))),
    axis=1).tolist()

# all the other columns used as properties
properties = psg_players_Final.drop(['Latitude', 'Longitude'], axis=1).to_dict('records')

# whole geojson object
feature_collection = FeatureCollection(features=features, properties=properties)

with open('psg_players_Final.geojson', 'w', encoding='utf-8') as f:
    json.dump(feature_collection, f, ensure_ascii=False)

psg_players_Final

,Player,Club,Nationality,Country,Latitude,Longitude
0,Keylor Navas,Paris Saint-Germain,Costa Rica,Costa Rica,10.00,-84.00
1,Sergio Rico,Paris Saint-Germain,Spain,Spain,40.00,-4.00
2,Marcin Bulka,Paris Saint-Germain,Poland,Poland,52.00,20.00
3,Alexandre Letellier,Paris Saint-Germain,France,France,46.00,2.00
4,Garissone Innocent,Paris Saint-Germain,Haiti,Haiti,19.00,-72.42
5,Denis Franchi,Paris Saint-Germain,Italy,Italy,42.83,12.83
6,Marquinhos,Paris Saint-Germain,Brazil,Brazil,-10.00,-55.00
7,Presnel Kimpembe,Paris Saint-Germain,France,France,46.00,2.00
8,Thilo Kehrer,Paris Saint-Germain,Germany,Germany,51.00,9.00
9,Abdou Diallo,Paris Saint-Germain,Senegal,Senegal,14.00,-14.00
10,Timothée Pembélé,Paris Saint-Germain,France,France,46.00,2.00
11,Juan Bernat,Paris Saint-Germain,Spain,Spain,40.00,-4.00
12,Layvin Kurzawa,Paris Saint-Germain,France,France,46.00,2.00
13,Colin Dagba,Paris Saint-Germain,France,France,46.00,2.00
14,Leandro Paredes,Paris Saint-Germain,Argentina,Argentina,-34.00,-64.00
15,Danilo Pereira,Paris Saint-Germain,Portugal,Portugal,39.50,-8.00
16,Idrissa Gueye,Paris Saint-Germain,Senegal,Senegal,14.00,-14.00
17,Marco Verratti,Paris Saint-Germain,Italy,Italy,42.83,12.83
18,Rafinha,Paris Saint-Germain,Brazil,Brazil,-10.00,-55.00
19,Ander Herrera,Paris Saint-Germain,Spain,Spain,40.00,-4.00
20,Xavi Simons,Paris Saint-Germain,Netherlands,Netherlands,52.50,5.75
21,Bandiougou Fadiga,Paris Saint-Germain,France,France,46.00,2.00
22,Edouard Michut,Paris Saint-Germain,France,France,46.00,2.00
23,Ismaël Gharbi,Paris Saint-Germain,France,France,46.00,2.00
24,Neymar,Paris Saint-Germain,Brazil,Brazil,-10.00,-55.00
25,Julian Draxler,Paris Saint-Germain,Germany,Germany,51.00,9.00
26,Pablo Sarabia,Paris Saint-Germain,Spain,Spain,40.00,-4.00
27,Ángel Di María,Paris Saint-Germain,Argentina,Argentina,-34.00,-64.00
28,Kylian Mbappé,Paris Saint-Germain,France,France,46.00,2.00
29,Mauro Icardi,Paris Saint-Germain,Argentina,Argentina,-34.00,-64.00
30,Arnaud Kalimuendo,Paris Saint-Germain,France,France,46.00,2.00
31,Kenny Nagera,Paris Saint-Germain,France,France,46.00,2.00

In [7]:
madrid_players = pd.read_csv('Resources/real_madrid_players.csv')
madrid_players_Final = pd.merge(madrid_players,Coordinates,how='left', left_on=['Nationality'], right_on=['Country'])

# columns used for constructing geojson object
features = madrid_players_Final.apply(
    lambda row: Feature(geometry=Point((float(row['Longitude']), float(row['Latitude'])))),
    axis=1).tolist()

# all the other columns used as properties
properties = madrid_players_Final.drop(['Latitude', 'Longitude'], axis=1).to_dict('records')

# whole geojson object
feature_collection = FeatureCollection(features=features, properties=properties)

with open('manchester_players_Final.geojson', 'w', encoding='utf-8') as f:
    json.dump(feature_collection, f, ensure_ascii=False)

madrid_players

,Player,Club,Nationality,Coordinates
0,Thibaut Courtois,Real Madrid,Belgium,"50.503887, 4.469936"
1,<<<<<<< HEAD,NaN,NaN,NaN
2,Andriy Lunin,Real Madrid,Ukraine,"48.379433,-31.16557999"
3,=======,NaN,NaN,NaN
4,Andriy Lunin,Real Madrid,Ukraine,"48.379433, 31.16558"
5,>>>>>>> 4a3c52d7ddb6079f3f49ffa21f84783b91971b27,NaN,NaN,NaN
6,Raphaël Varane,Real Madrid,France,"46.227638, 2.213749"
7,Éder Militão,Real Madrid,Brazil,"-14.235004, -51.92528"
8,Nacho Fernández,Real Madrid,Spain,"40.463667, -3.74922"
9,Ferland Mendy,Real Madrid,France,"46.227638, 2.213749"
10,Marcelo,Real Madrid,Brazil,"-14.235004, -51.92528"
11,Daniel Carvajal,Real Madrid,Spain,"40.463667, -3.74922"
12,Álvaro Odriozola,Real Madrid,Spain,"40.463667, -3.74922"
13,Casemiro,Real Madrid,Brazil,"-14.235004, -51.92528"
14,<<<<<<< HEAD,NaN,NaN,NaN
15,Fede Valverde,Real Madrid,Uruguay,"-32.522779,-55.765835"
16,Toni Kroos,Real Madrid,Germany,"51.165691, 10.451526"
17,Luka Modric,Real Madrid,Croatia,"45.1, 15.2"
18,Martin Ødegaard,Real Madrid,Norway,"66.76667,14.899925"
19,=======,NaN,NaN,NaN
20,Fede Valverde,Real Madrid,Uruguay,"-32.522779, -55.765835"
21,Toni Kroos,Real Madrid,Germany,"51.165691, 10.451526"
22,Luka Modric,Real Madrid,Croatia,"45.1, 15.2"
23,Martin Ødegaard,Real Madrid,Norway,"60.472024, 8.468946"
24,>>>>>>> 4a3c52d7ddb6079f3f49ffa21f84783b91971b27,NaN,NaN,NaN
25,Isco,Real Madrid,Spain,"40.463667, -3.74922"
26,Eden Hazard,Real Madrid,Belgium,"50.503887, 4.469936"
27,Vinícius Júnior,Real Madrid,Brazil,"-14.235004, -51.92528"
28,Marco Asensio,Real Madrid,Spain,"40.463667, -3.74922"
29,Rodrygo,Real Madrid,Brazil,"-14.235004, -51.92528"
30,Lucas Vázquez,Real Madrid,Spain,"40.463667, -3.74922"
31,Karim Benzema,Real Madrid,France,"46.227638, 2.213749"
32,<<<<<<< HEAD,NaN,NaN,NaN
33,Luka Jovic,Real Madrid,Serbia,"44.23297,20.797958"
34,Mariano Díaz,Real Madrid,Dominican Republic,"18.483402,-69.929611"
35,=======,NaN,NaN,NaN
36,Luka Jovic,Real Madrid,Serbia,"44.016521, 21.005859"
37,Mariano Díaz,Real Madrid,Dominican Republic,"18.735693, -70.162651"
38,>>>>>>> 4a3c52d7ddb6079f3f49ffa21f84783b91971b27,NaN,NaN,NaN

In [5]:
chelsea_group = chelsea_players.groupby("Nationality").agg({"Nationality":["count"]})
#nationality_group.reset_index(inplace=True)
#nationality_group.columns = ["Nationality","Count"]
#Sorted_nationalities = nationality_group.sort_values(by = "Count", ascending = False)
#Sorted_nationalities

In [6]:
manchester_players

                 Player             Club    Nationality
0               Ederson  Manchester City         Brazil
1          Zack Steffen  Manchester City  United States
2            Rúben Dias  Manchester City       Portugal
3       Aymeric Laporte  Manchester City          Spain
4            Nathan Aké  Manchester City    Netherlands
5           John Stones  Manchester City        England
6      Philippe Sandler  Manchester City    Netherlands
7   Oleksandr Zinchenko  Manchester City        Ukraine
8        Benjamin Mendy  Manchester City         France
9          João Cancelo  Manchester City       Portugal
10          Kyle Walker  Manchester City        England
11                Rodri  Manchester City          Spain
12          Fernandinho  Manchester City         Brazil
13       Ilkay Gündogan  Manchester City        Germany
14      Kevin De Bruyne  Manchester City        Belgium
15       Bernardo Silva  Manchester City       Portugal
16      Raheem Sterling  Manchester City        England
17           Phil Foden  Manchester City        England
18        Ferran Torres  Manchester City          Spain
19         Riyad Mahrez  Manchester City        Algeria
20      Patrick Roberts  Manchester City        England
21        Gabriel Jesus  Manchester City         Brazil

In [7]:
psg_players

                 Player                 Club  Nationality
0          Keylor Navas  Paris Saint-Germain   Costa Rica
1           Sergio Rico  Paris Saint-Germain        Spain
2          Marcin Bulka  Paris Saint-Germain       Poland
3   Alexandre Letellier  Paris Saint-Germain       France
4    Garissone Innocent  Paris Saint-Germain        Haiti
5         Denis Franchi  Paris Saint-Germain        Italy
6            Marquinhos  Paris Saint-Germain       Brazil
7      Presnel Kimpembe  Paris Saint-Germain       France
8          Thilo Kehrer  Paris Saint-Germain      Germany
9          Abdou Diallo  Paris Saint-Germain      Senegal
10     Timothée Pembélé  Paris Saint-Germain       France
11          Juan Bernat  Paris Saint-Germain        Spain
12       Layvin Kurzawa  Paris Saint-Germain       France
13          Colin Dagba  Paris Saint-Germain       France
14      Leandro Paredes  Paris Saint-Germain    Argentina
15       Danilo Pereira  Paris Saint-Germain     Portugal
16        Idrissa Gueye  Paris Saint-Germain      Senegal
17       Marco Verratti  Paris Saint-Germain        Italy
18              Rafinha  Paris Saint-Germain       Brazil
19        Ander Herrera  Paris Saint-Germain        Spain
20          Xavi Simons  Paris Saint-Germain  Netherlands
21    Bandiougou Fadiga  Paris Saint-Germain       France
22       Edouard Michut  Paris Saint-Germain       France
23        Ismaël Gharbi  Paris Saint-Germain       France
24               Neymar  Paris Saint-Germain       Brazil
25       Julian Draxler  Paris Saint-Germain      Germany
26        Pablo Sarabia  Paris Saint-Germain        Spain
27       Ángel Di María  Paris Saint-Germain    Argentina
28        Kylian Mbappé  Paris Saint-Germain       France
29         Mauro Icardi  Paris Saint-Germain    Argentina
30    Arnaud Kalimuendo  Paris Saint-Germain       France
31         Kenny Nagera  Paris Saint-Germain       France

In [8]:
madrid_players

              Player         Club         Nationality
0   Thibaut Courtois  Real Madrid             Belgium
1       Andriy Lunin  Real Madrid             Ukraine
2     Raphaël Varane  Real Madrid              France
3       Éder Militão  Real Madrid              Brazil
4    Nacho Fernández  Real Madrid               Spain
5      Ferland Mendy  Real Madrid              France
6            Marcelo  Real Madrid              Brazil
7    Daniel Carvajal  Real Madrid               Spain
8   Álvaro Odriozola  Real Madrid               Spain
9           Casemiro  Real Madrid              Brazil
10     Fede Valverde  Real Madrid             Uruguay
11        Toni Kroos  Real Madrid             Germany
12       Luka Modric  Real Madrid             Croatia
13   Martin Ødegaard  Real Madrid              Norway
14              Isco  Real Madrid               Spain
15       Eden Hazard  Real Madrid             Belgium
16   Vinícius Júnior  Real Madrid              Brazil
17     Marco Asensio  Real Madrid               Spain
18           Rodrygo  Real Madrid              Brazil
19     Lucas Vázquez  Real Madrid               Spain
20     Karim Benzema  Real Madrid              France
21        Luka Jovic  Real Madrid              Serbia
22      Mariano Díaz  Real Madrid  Dominican Republic

In [9]:
frames = [chelsea_players, manchester_players, psg_players,madrid_players]
all_nationalities = pd.concat(frames)
all_nationalities

                 Player         Club         Nationality
0         Edouard Mendy   Chelsea FC             Senegal
1                  Kepa   Chelsea FC               Spain
2            Kurt Zouma   Chelsea FC              France
3   Andreas Christensen   Chelsea FC             Denmark
4       Antonio Rüdiger   Chelsea FC             Germany
..                  ...          ...                 ...
18              Rodrygo  Real Madrid              Brazil
19        Lucas Vázquez  Real Madrid               Spain
20        Karim Benzema  Real Madrid              France
21           Luka Jovic  Real Madrid              Serbia
22         Mariano Díaz  Real Madrid  Dominican Republic

[106 rows x 3 columns]

In [10]:
nationality_group = all_nationalities.groupby(["Club","Nationality"]).agg({"Nationality":["count"]})
nationality_group.reset_index(inplace=True)
nationality_group.columns = ["Club","Nationality","Count"]
Sorted_nationalities = nationality_group.sort_values(by = "Club", ascending = False)
Sorted_nationalities

                   Club         Nationality  Count
46          Real Madrid             Uruguay      1
41          Real Madrid             Germany      1
37          Real Madrid              Brazil      5
38          Real Madrid             Croatia      1
39          Real Madrid  Dominican Republic      1
40          Real Madrid              France      3
36          Real Madrid             Belgium      2
42          Real Madrid              Norway      1
43          Real Madrid              Serbia      1
44          Real Madrid               Spain      6
45          Real Madrid             Ukraine      1
24  Paris Saint-Germain           Argentina      3
35  Paris Saint-Germain               Spain      4
34  Paris Saint-Germain             Senegal      2
33  Paris Saint-Germain            Portugal      1
32  Paris Saint-Germain              Poland      1
31  Paris Saint-Germain         Netherlands      1
30  Paris Saint-Germain               Italy      2
29  Paris Saint-Germain               Haiti      1
28  Paris Saint-Germain             Germany      2
27  Paris Saint-Germain              France     11
26  Paris Saint-Germain          Costa Rica      1
25  Paris Saint-Germain              Brazil      3
23      Manchester City       United States      1
21      Manchester City               Spain      3
20      Manchester City            Portugal      3
19      Manchester City         Netherlands      2
18      Manchester City             Germany      1
17      Manchester City              France      1
16      Manchester City             England      5
15      Manchester City              Brazil      3
14      Manchester City             Belgium      1
13      Manchester City             Algeria      1
22      Manchester City             Ukraine      1
1            Chelsea FC              Brazil      1
6            Chelsea FC             Germany      3
2            Chelsea FC             Croatia      1
3            Chelsea FC             Denmark      1
4            Chelsea FC             England      9
5            Chelsea FC              France      3
12           Chelsea FC               Wales      1
7            Chelsea FC               Italy      2
8            Chelsea FC             Morocco      1
9            Chelsea FC             Senegal      1
10           Chelsea FC               Spain      3
11           Chelsea FC       United States      1
0            Chelsea FC             Belgium      2

In [12]:
html_table = nationality_group.to_html()
html_table

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Club</th>\n      <th>Nationality</th>\n      <th>Count</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Chelsea FC</td>\n      <td>Belgium</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Chelsea FC</td>\n      <td>Brazil</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Chelsea FC</td>\n      <td>Croatia</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Chelsea FC</td>\n      <td>Denmark</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Chelsea FC</td>\n      <td>England</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Chelsea FC</td>\n      <td>France</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Chelsea FC</td>\n      <td>Germany</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Chelsea FC</td>\n      <td>Italy</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Chelsea FC</td>\n      <td>Morocco</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Chelsea FC</td>\n      <td>Senegal</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>Chelsea FC</td>\n      <td>Spain</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Chelsea FC</td>\n      <td>United States</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>Chelsea FC</td>\n      <td>Wales</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>Manchester City</td>\n      <td>Algeria</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>Manchester City</td>\n      <td>Belgium</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>Manchester City</td>\n      <td>Brazil</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>Manchester City</td>\n      <td>England</td>\n      <td>5</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>Manchester City</td>\n      <td>France</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>Manchester City</td>\n      <td>Germany</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>Manchester City</td>\n      <td>Netherlands</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>Manchester City</td>\n      <td>Portugal</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>Manchester City</td>\n      <td>Spain</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>Manchester City</td>\n      <td>Ukraine</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>Manchester City</td>\n      <td>United States</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>Paris Saint-Germain</td>\n      <td>Argentina</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>25</th>\n      <td>Paris Saint-Germain</td>\n      <td>Brazil</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>26</th>\n      <td>Paris Saint-Germain</td>\n      <td>Costa Rica</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>27</th>\n      <td>Paris Saint-Germain</td>\n      <td>France</td>\n      <td>11</td>\n    </tr>\n    <tr>\n      <th>28</th>\n      <td>Paris Saint-Germain</td>\n      <td>Germany</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>29</th>\n      <td>Paris Saint-Germain</td>\n      <td>Haiti</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>30</th>\n      <td>Paris Saint-Germain</td>\n      <td>Italy</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>31</th>\n      <td>Paris Saint-Germain</td>\n      <td>Netherlands</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>32</th>\n      <td>Paris Saint-Germain</td>\n      <td>Poland</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>33</th>\n      <td>Paris Saint-Germain</td>\n      <td>Portugal</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>34</th>\n      <td>Paris Saint-Germain</td>\n      <td>Senegal</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>35</th>\n      <td>Paris Saint-Germain</td>\n      <td>Spain</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>36</th>\n      <td>Real Madrid</td>\n      <td>Belgium</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>37</th>\n      <td>Real Madrid</td>\n      <td>Brazil</td>\n      <td>5</td>\n    </tr>\n    <tr>\n      <th>38</th>\n      <td>Real Madrid</td>\n      <td>Croatia</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>39</th>\n      <td>Real Madrid</td>\n      <td>Dominican Republic</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>40</th>\n      <td>Real Madrid</td>\n      <td>France</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>41</th>\n      <td>Real Madrid</td>\n      <td>Germany</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>42</th>\n      <td>Real Madrid</td>\n      <td>Norway</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>43</th>\n      <td>Real Madrid</td>\n      <td>Serbia</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>44</th>\n      <td>Real Madrid</td>\n      <td>Spain</td>\n      <td>6</td>\n    </tr>\n    <tr>\n      <th>45</th>\n      <td>Real Madrid</td>\n      <td>Ukraine</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>46</th>\n      <td>Real Madrid</td>\n      <td>Uruguay</td>\n      <td>1</td>\n    </tr>\n  </tbody>\n</table>'

In [18]:
nationality_group.to_html('Data_table.html')

## Foreign Player Minutes

In [11]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# Premier League
league = "premier-league"
abbr = "GB1"
r = requests.get(f"https://www.transfermarkt.co.uk/{league}/legionaereeinsaetze/wettbewerb/{abbr}/saison_id/2020/altersklasse/alle/option/spiele/plus/1", 
                 headers= {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"})
soup = BeautifulSoup(r.content, "html.parser")

In [3]:
results = soup.find("table",class_="items")
premier_leauge_minutes = pd.read_html(str(results))[0]
premier_leauge_minutes.drop(columns=['wappen',"% minutes foreign players"],inplace=True)
premier_leauge_minutes.columns=['Club', 'Players used', 'Non-foreigners played',
       'Used foreign players', '% minutes non-foreigners',
       '% minutes foreign players']
premier_leauge_minutes = premier_leauge_minutes[:20]
premier_leauge_minutes = premier_leauge_minutes.sort_values(by="% minutes foreign players", ascending=False)
premier_leauge_minutes

,Club,Players used,Non-foreigners played,Used foreign players,% minutes non-foreigners,% minutes foreign players
19,Wolves,27,4,23,13.6 %,86.4 %
18,Spurs,24,6,18,20.1 %,79.9 %
17,Man City,24,6,18,21.8 %,78.2 %
16,Arsenal,29,8,21,22.7 %,77.3 %
15,Chelsea,27,8,19,26.1 %,73.9 %
14,Liverpool,28,8,20,26.4 %,73.6 %
13,Fulham,28,7,21,29.7 %,70.3 %
12,Leicester,27,8,19,31.9 %,68.1 %
11,Leeds,23,7,16,33.5 %,66.5 %
10,Crystal Palace,24,10,14,36.5 %,63.5 %
9,West Ham,24,8,16,36.7 %,63.3 %
8,Man Utd,29,10,19,40.6 %,59.4 %
7,Everton,29,10,19,41.1 %,58.9 %
6,Newcastle,27,11,16,42.1 %,57.9 %
5,Brighton,27,8,19,43.9 %,56.1 %
4,Sheff Utd,27,15,12,49.5 %,50.5 %
3,West Brom,30,16,14,53.3 %,46.7 %
2,Southampton,29,13,16,53.9 %,46.1 %
1,Aston Villa,24,12,12,55.3 %,44.7 %
0,Burnley,25,15,10,75.1 %,24.9 %

In [12]:
engine = create_engine('sqlite:///football.db')

In [13]:
premier_leauge_minutes.to_sql('premier_league_foreign_minutes', con=engine, if_exists='replace', index=False)

In [14]:
engine.execute("SELECT * FROM premier_league_foreign_minutes").fetchall()

[('Wolves', '27', 4, 23, '13.6 %', '86.4 %'),
 ('Spurs', '24', 6, 18, '20.1 %', '79.9 %'),
 ('Man City', '24', 6, 18, '21.8 %', '78.2 %'),
 ('Arsenal', '29', 8, 21, '22.7 %', '77.3 %'),
 ('Chelsea', '27', 8, 19, '26.1 %', '73.9 %'),
 ('Liverpool', '28', 8, 20, '26.4 %', '73.6 %'),
 ('Fulham', '28', 7, 21, '29.7 %', '70.3 %'),
 ('Leicester', '27', 8, 19, '31.9 %', '68.1 %'),
 ('Leeds', '23', 7, 16, '33.5 %', '66.5 %'),
 ('Crystal Palace', '24', 10, 14, '36.5 %', '63.5 %'),
 ('West Ham', '24', 8, 16, '36.7 %', '63.3 %'),
 ('Man Utd', '29', 10, 19, '40.6 %', '59.4 %'),
 ('Everton', '29', 10, 19, '41.1 %', '58.9 %'),
 ('Newcastle', '27', 11, 16, '42.1 %', '57.9 %'),
 ('Brighton', '27', 8, 19, '43.9 %', '56.1 %'),
 ('Sheff Utd', '27', 15, 12, '49.5 %', '50.5 %'),
 ('West Brom', '30', 16, 14, '53.3 %', '46.7 %'),
 ('Southampton', '29', 13, 16, '53.9 %', '46.1 %'),
 ('Aston Villa', '24', 12, 12, '55.3 %', '44.7 %'),
 ('Burnley', '25', 15, 10, '75.1 %', '24.9 %')]

In [9]:
# Ligue 1
league = "ligue-1"
abbr = "FR1"

r = requests.get(f"https://www.transfermarkt.co.uk/{league}/legionaereeinsaetze/wettbewerb/{abbr}/saison_id/2020/altersklasse/alle/option/spiele/plus/1", 
                 headers= {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"})
soup = BeautifulSoup(r.content, "html.parser")

In [10]:
results = soup.find("table",class_="items")
ligue_one_minutes = pd.read_html(str(results))[0]
ligue_one_minutes.drop(columns=['wappen',"% minutes foreign players"],inplace=True)
ligue_one_minutes.columns=['Club', 'Players used', 'Non-foreigners played',
       'Used foreign players', '% minutes non-foreigners',
       '% minutes foreign players']
ligue_one_minutes = ligue_one_minutes[:20]
ligue_one_minutes = ligue_one_minutes.sort_values(by="% minutes foreign players", ascending=False)
ligue_one_minutes

,Club,Players used,Non-foreigners played,Used foreign players,% minutes non-foreigners,% minutes foreign players
19,Stade Reims,29,7,22,19.5 %,80.5 %
18,Paris SG,33,10,23,21.4 %,78.6 %
17,Olympique Lyon,29,10,19,22.1 %,77.9 %
16,FC Metz,27,9,18,26.0 %,74.0 %
15,Dijon,33,13,20,27.5 %,72.5 %
14,LOSC Lille,21,8,13,37.4 %,62.6 %
13,OGC Nice,31,17,14,49.2 %,50.8 %
12,Nîmes Olympique,34,18,16,49.4 %,50.6 %
11,R. Strasbourg,26,12,14,50.8 %,49.2 %
10,G. Bordeaux,28,14,14,52.2 %,47.8 %
9,Marseille,31,18,13,52.8 %,47.2 %
8,Lens,27,14,13,57.9 %,42.1 %
7,FC Nantes,25,14,11,59.5 %,40.5 %
6,SCO Angers,31,19,12,60.4 %,39.6 %
5,Montpellier,25,15,10,60.5 %,39.5 %
4,Saint-Étienne,40,28,12,60.6 %,39.4 %
3,Monaco,30,13,17,61.5 %,38.5 %
2,FC Lorient,27,16,11,64.2 %,35.8 %
1,Stade Rennais,32,22,10,67.7 %,32.3 %
0,Stade Brest 29,26,19,7,77.4 %,22.6 %

In [15]:
ligue_one_minutes.to_sql('ligue__one_foreign_minutes', con=engine, if_exists='replace', index=False)

In [18]:
engine.execute("SELECT * FROM ligue__one_foreign_minutes").fetchall()

[('Stade Reims', '29', 7, 22, '19.5 %', '80.5 %'),
 ('Paris SG', '33', 10, 23, '21.4 %', '78.6 %'),
 ('Olympique Lyon', '29', 10, 19, '22.1 %', '77.9 %'),
 ('FC Metz', '27', 9, 18, '26.0 %', '74.0 %'),
 ('Dijon', '33', 13, 20, '27.5 %', '72.5 %'),
 ('LOSC Lille', '21', 8, 13, '37.4 %', '62.6 %'),
 ('OGC Nice', '31', 17, 14, '49.2 %', '50.8 %'),
 ('Nîmes Olympique', '34', 18, 16, '49.4 %', '50.6 %'),
 ('R. Strasbourg', '26', 12, 14, '50.8 %', '49.2 %'),
 ('G. Bordeaux', '28', 14, 14, '52.2 %', '47.8 %'),
 ('Marseille', '31', 18, 13, '52.8 %', '47.2 %'),
 ('Lens', '27', 14, 13, '57.9 %', '42.1 %'),
 ('FC Nantes', '25', 14, 11, '59.5 %', '40.5 %'),
 ('SCO Angers', '31', 19, 12, '60.4 %', '39.6 %'),
 ('Montpellier', '25', 15, 10, '60.5 %', '39.5 %'),
 ('Saint-Étienne', '40', 28, 12, '60.6 %', '39.4 %'),
 ('Monaco', '30', 13, 17, '61.5 %', '38.5 %'),
 ('FC Lorient', '27', 16, 11, '64.2 %', '35.8 %'),
 ('Stade Rennais', '32', 22, 10, '67.7 %', '32.3 %'),
 ('Stade Brest 29', '26', 19, 7, '77.4 %', '22.6 %')]

In [6]:
# La Liga
league = "laliga"
abbr = "ES1"
r = requests.get(f"https://www.transfermarkt.co.uk/{league}/legionaereeinsaetze/wettbewerb/{abbr}/saison_id/2020/altersklasse/alle/option/spiele/plus/1", 
                 headers= {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"})
soup = BeautifulSoup(r.content, "html.parser")

In [7]:
results = soup.find("table",class_="items")
laliga_minutes = pd.read_html(str(results))[0]
laliga_minutes.drop(columns=['wappen',"% minutes foreign players"],inplace=True)
laliga_minutes.columns=['Club', 'Players used', 'Non-foreigners played',
       'Used foreign players', '% minutes non-foreigners',
       '% minutes foreign players']
laliga_minutes = laliga_minutes[:20]
laliga_minutes = laliga_minutes.sort_values(by="% minutes foreign players", ascending=False)
laliga_minutes

,Club,Players used,Non-foreigners played,Used foreign players,% minutes non-foreigners,% minutes foreign players
19,Real Madrid,30,14,16,28.3 %,71.7 %
18,Atlético Madrid,25,8,17,29.7 %,70.3 %
17,Sevilla FC,26,10,16,30.4 %,69.6 %
16,Valencia,30,11,19,35.2 %,64.8 %
15,Barcelona,25,11,14,37.0 %,63.0 %
14,Getafe,31,13,18,41.0 %,59.0 %
13,Granada CF,34,20,14,48.1 %,51.9 %
12,Real Betis,25,14,11,51.7 %,48.3 %
11,SD Eibar,30,21,9,61.2 %,38.8 %
10,Cádiz CF,34,23,11,62.1 %,37.9 %
9,Celta de Vigo,30,19,11,66.4 %,33.6 %
8,Elche CF,30,18,12,68.2 %,31.8 %
7,Real Valladolid,32,24,8,72.2 %,27.8 %
6,Levante,29,20,9,72.2 %,27.8 %
5,Alavés,30,21,9,79.3 %,20.7 %
4,Villarreal,29,19,10,79.8 %,20.2 %
3,Real Sociedad,30,25,5,80.3 %,19.7 %
2,SD Huesca,27,20,7,82.7 %,17.3 %
1,CA Osasuna,28,22,6,84.5 %,15.5 %
0,Athletic,27,26,1,99.9 %,0.1 %

In [16]:
laliga_minutes.to_sql('laliga_foreign_minutes', con=engine, if_exists='replace', index=False)

In [19]:
engine.execute("SELECT * FROM laliga_foreign_minutes").fetchall()

[('Real Madrid', '30', 14, 16, '28.3 %', '71.7 %'),
 ('Atlético Madrid', '25', 8, 17, '29.7 %', '70.3 %'),
 ('Sevilla FC', '26', 10, 16, '30.4 %', '69.6 %'),
 ('Valencia', '30', 11, 19, '35.2 %', '64.8 %'),
 ('Barcelona', '25', 11, 14, '37.0 %', '63.0 %'),
 ('Getafe', '31', 13, 18, '41.0 %', '59.0 %'),
 ('Granada CF', '34', 20, 14, '48.1 %', '51.9 %'),
 ('Real Betis', '25', 14, 11, '51.7 %', '48.3 %'),
 ('SD Eibar', '30', 21, 9, '61.2 %', '38.8 %'),
 ('Cádiz CF', '34', 23, 11, '62.1 %', '37.9 %'),
 ('Celta de Vigo', '30', 19, 11, '66.4 %', '33.6 %'),
 ('Elche CF', '30', 18, 12, '68.2 %', '31.8 %'),
 ('Real Valladolid', '32', 24, 8, '72.2 %', '27.8 %'),
 ('Levante', '29', 20, 9, '72.2 %', '27.8 %'),
 ('Alavés', '30', 21, 9, '79.3 %', '20.7 %'),
 ('Villarreal', '29', 19, 10, '79.8 %', '20.2 %'),
 ('Real Sociedad', '30', 25, 5, '80.3 %', '19.7 %'),
 ('SD Huesca', '27', 20, 7, '82.7 %', '17.3 %'),
 ('CA Osasuna', '28', 22, 6, '84.5 %', '15.5 %'),
 ('Athletic', '27', 26, 1, '99.9 %', '0.1 %')]